version: '3.9'

services:
  grafana:
    image: grafana/grafana:8.2.1
    container_name: mk_grafana
    restart: always
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    container_name: mk_cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    labels:
      org.label-schema.group: "monitoring"
  
  prometheus:
    image: prom/prometheus
    user: ${CURRENT_USER}
    container_name: mk_prometheus
    restart: always
    environment:
      - MIKROTIK_IP=${MIKROTIK_IP}
    volumes:
      - ./prometheus/:/etc/prometheus
      - ./prometheus/data/:/prometheus
    ports:
      - "9090:9090"

  node-exporter:
    image: 'prom/node-exporter:latest'
    container_name: mk_node_exporter
    user: root
    privileged: true
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
#    networks:
#      testlab:
#        ipv4_address: 10.0.0.20
    expose:
      - 9100
    ports:
      - '9100:9100'

  snmp_exporter:
    image: mashinkopochinko/snmp_exporter_mikrotik
    container_name: mk_snmp_exporter
    restart: always
    ports:
      - "9116:9116"
    depends_on:
      - prometheus

  mktxp:
    restart: on-failure
    image: guenterbailey/mktxp:latest
    container_name: mk_txp_exporter
    volumes:
      - /home/dietpi/home-network-monitoring/mktxp:/root/mktxp:rw
    ports:
      - "192.168.88.2:49090:49090"
    depends_on:
      - prometheus

  pihole:
    image: ekofr/pihole-exporter:latest
    container_name: mk_pihole_exporter
    restart: always
    environment:
      - PIHOLE_HOSTNAME=192.168.88.2
      - PIHOLE_PASSWORD=!#Destiny/1989#!
      - INTERVAL=5s
      - PORT=9617
    ports:
      - "9617:9617"
    depends_on:
      - prometheus