global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'Mikrotik'

scrape_configs:
  - job_name: 'Prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'Cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'Pihole'
    static_configs:
      - targets: ['0.0.0.0:9617']

  - job_name: 'Tx201'
    static_configs:
      - targets: ['0.0.0.0:9100']

  - job_name: 'Mktxp'
    static_configs:
      - targets: ['0.0.0.0:49090']     
    
  - job_name: 'Rpi3b'
    static_configs:
      - targets: ['192.168.88.3:9100']

  - job_name: 'Tx1y4'
    static_configs:
      - targets: ['192.168.88.87:9100']

  - job_name: Mikrotik
    static_configs:
      - targets:
        - 192.168.88.1 # mikrotik_ip
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 0.0.0.0:9116  # The SNMP exporter's real hostname:port.
